### ISSUE TITLE
Combination types not correctly fontitied

### ISSUE THREAD

**Issue by rNoz** [Fuco1/flow-js2-mode#10]
Hi,

```js
function some(a: number | string, b: {} | any[]) : bool {
  return true;
}
```

Gives `number` without font-lock-type-face (but `string` is correct).

Also, thanks for this mode, I really like it (and need it).

Are you planning to support `Promise<any>`,  `Array<any>`?

**Comment by Fuco1** [comment]
Thanks for the report!

I plan to support everything eventually :) I'm quite new to JS/Flow so I pretty much fix things as I come along the problems, so reporting issues definitely speed up the process!  Generics work for some cases but probably not yet those you describe.  I will open a separate issue to track that and keep this for the font-lock.

**Comment by Fuco1** [comment]
FYI generics like `Promise<T>` should work on master now.
