### ISSUE TITLE
Support for generics in arrow functions

### ISSUE THREAD

**Issue by gitonthescene** [Fuco1/flow-js2-mode#22]
Hi there,

I read that you're not using flow any more, but might accept pull requests.  I have a small change which allows it to parse generics in arrow functions like the following:

export function useDraftForm2<T>(basestate: T) {
  const var2 = 3;
};

(ref: https://flow.org/en/docs/types/generics/)

Should I just submit the request?  I see some other issues that I might take a crack at as well, but I'm still wrapping my head around js2-mode.

Thanks,
-Doug

**Comment by Fuco1** [comment]
Yes please.  I'm still using flow on "legacy" projects which we aren't planning to migrate to typescript, so I can justify setting some time aside to review it.

`js2-mode` is a hell of its own so don't worry ;D

**Comment by gitonthescene** [comment]
Thanks!  I'll post it later this afternoon.  FWIW, I just realized I messed up the cut-and-paste.  I'm trying to cover this case:

export const useDraftForm2 = <T>(basestate: T) => {
  const var2 = 3;
};

You already handle the case posted above.

**Comment by gitonthescene** [comment]
Pulled with PR #23.
